# Generated by Django 5.1.6 on 2025-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100)),
                ('caller_number', models.CharField(max_length=20)),
                ('callee_number', models.CharField(max_length=20)),
                ('call_start_time', models.DateTimeField()),
                ('call_end_time', models.DateTimeField()),
                ('call_duration', models.IntegerField()),
                ('call_type', models.CharField(max_length=20)),
            ],
        ),
    ]
