# Generated by Django 5.1.6 on 2025-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailrecord',
            name='call_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calldetailrecord',
            name='call_recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='calldetailrecord',
            name='is_suspect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calldetailrecord',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calldetailrecord',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='call_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('missed', 'Missed'), ('voicemail', 'Voicemail')], max_length=20),
        ),
    ]
