# Generated by Django 5.1.6 on 2025-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_app', '0002_calldetailrecord_call_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailrecord',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
